### ISSUE TITLE
Dependency hell - cannot install ccpi-reconstruction build from sources

### ISSUE THREAD

**Issue by TomasKulhanek** [vais-ral/CCPi-VirtualMachine#13]
- lot of ccpi packages require numpy=1.12 and python=3.5, should be considered to upgrade to latest numpy and lates python
- very fragile environment when need to install e.g. gnu octave, jupyter, machine learning libraries (rdkit, sklearn) or other

**Comment by paskino** [comment]
Build variants is what I'd like you to address with Jenkins.

Dependencies are currently taken care of with conda

**Comment by paskino** [comment]
@TomasKulhanek do you have any experience with jupyter widgets like[interact](https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html)? I'd like to create an app which connects to an ipython kernel which may run locally or remotely.

**Comment by TomasKulhanek** [comment]
- `pip` is used to install sos-polyglot, nglview, ssbio, autosklearn into virtual env created by conda as it is recommended for non-conda packages in https://conda.io/docs/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages There wasn't conda packages or there were errors in the time of creation of this scripts (6-12 months ago), effort could be invested to check whether conda packages are available now. Anyway disabling all pip-packages doesn't relate to the originaly reported dependency hell
- ccpi-astra astratoolbox and others identified by `conda` as not-compatible with jupyter, gnu octave, gnuplot and others if installed at the end. 

Current workaround: install all ccpi related stuff first before other non-ccpi (jupyter, octave) etc. by conda.

**Comment by TomasKulhanek** [comment]
@paskino: "do you have any experience...". No. I've used REST Api, ajax calls and direct visualization rendered from html/javascript to interact with local or remote web services.
