### ISSUE TITLE
Build of packages should use conda-build

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-VirtualMachine#2]
For instance building the CCPi-Regularisation-Toolkit https://github.com/vais-ral/CCPi-VirtualMachine/blob/master/vm-from-sources/bootstrapsrc.sh#L42 does not use conda build.

It should do something like 
```python
conda install conda-build
cd CCPi-Regularisation-Toolkit-src
conda build Wrappers/Python/conda-recipe -c ccpi -c conda-forge
conda install ccpi-regulariser
```
which would also run unittest.

**Comment by TomasKulhanek** [comment]
Then it is confusing in https://github.com/vais-ral/CCPi-Regularisation-Toolkit/blob/master/Readme.md. Section about `conda-build` seems to be related to binary installation.
I suggest to review documentation and update the bootstrapsrc.sh appropriately.

**Comment by paskino** [comment]
The Regularisation-Toolkit comes as a CMake package with MATLAB and Python wrappers, which are optional. The documentation describes the build options. 

As conda is only Python specific (not exactly true), the instruction on how to build with conda are in the Python section, but I agree there should be a little explanation. 

The conda build is not really good for developing when you need to recompile often and debug. 
But in the current case you are installing the package in a conda environment and it makes very much sense to build with `conda-build`.

My point is that all our packages should come as CMake package to ease the build. Additionally they should contain a conda-recipe to create the conda package. For users installing the conda package in the  conda environment installing a conda package should be sufficient, even if they may build it themselves with `conda-build`. The developer may instead be interested in using bare CMake for build/debug.

**Comment by TomasKulhanek** [comment]
added conda build and conda install for Regularisation into bootstrapsrc.sh

**Comment by paskino** [comment]
I guess [these](https://github.com/vais-ral/CCPi-VirtualMachine/blob/master/vm-from-sources/bootstrapsrc.sh#L42-L45) lines should go?

**Comment by TomasKulhanek** [comment]
Again, confused, so cmake and conda are interchangeable? Alternatives to build from sources? Or with cmake I can build something more, with conda something less?
It should be clearly stated in documentation.

**Comment by paskino** [comment]
I see it like this:

1. To build our software we should use CMake. 
2. Python wrapper to the code should be available for every package
2. To distribute our software (python wrappers) the preferred method is the anaconda channel

Not all our packages come as pure CMake packages yet, but they have a conda recipe.

Additionally, conda builds are used only for the Python wrappers, but some repos do have wrappers for MATLAB, Avizo, Paraview or ImageJ.

**Comment by TomasKulhanek** [comment]
Original request implemented - bootstrapsrc uses conda-build
