### ISSUE TITLE
Build fails on anaconda empty filename

### ISSUE THREAD

**Issue by TomasKulhanek** [vais-ral/CCPi-VirtualMachine#22]
Build fails on anaconda empty filename

conda package located at:
https://anaconda.org/ccpi/ccpi-regulariser

usage: anaconda upload [-h] [-c CHANNELS] [-l LABELS] [--no-progress]
                       [-u USER] [--all] [-p PACKAGE] [-v VERSION]
                       [-s SUMMARY] [-t PACKAGE_TYPE] [-d DESCRIPTION]
                       [--thumbnail THUMBNAIL] [--private]
                       [--no-register | --register] [--build-id BUILD_ID]
                       [-i | -f | --force | --skip-existing]
                       files [files ...]
anaconda upload: error: the following arguments are required: files
Build step 'Execute shell' marked build as failure
Sending e-mails to: 
[Set GitHub commit status (universal)] PENDING on repos [] (sha:49b2f86) with context:CILsingle/CCPi-Regularisation-Toolkit
Finished: FAILURE

**Comment by paskino** [comment]
Do you know how that empty file name came about?

**Comment by TomasKulhanek** [comment]
I’m working on it https://github.com/vais-ral/CCPi-VirtualMachine/issues/22
