### ISSUE TITLE
CILViewer master Jenkins fails to detect branch

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-VirtualMachine#25]
On the CILViewer repo, Jenkins detects the master branch as `HEAD` and then does not upload.

```
++ git rev-parse --symbolic-full-name HEAD
+ GIT_BRANCH=HEAD
+ echo on branch HEAD
on branch HEAD

...

+ [[ HEAD == \r\e\f\s\/\h\e\a\d\s\/\m\a\s\t\e\r ]]
+ echo git branch is not master, will not upload to anaconda.
git branch is not master, will not upload to anaconda.
```
In Jenkins build 6 I added `git checkout master`. With it Jenkins detects the `master` branch correctly, wrt build 5 when it detected the branch as `HEAD`.

What's the difference with other repos?

**Comment by TomasKulhanek** [comment]
https://cil.readthedocs.io/en/latest/buildandtestautomation.html#production-built-for-ccpi-module-name 2.c.c. Additional Behaviours, Check out to specific local branch

**Comment by TomasKulhanek** [comment]
applied the conf in jenkins as documented in https://cil.readthedocs.io/en/latest/buildandtestautomation.html#production-built-for-ccpi-module-name 2.c.c. Additional Behaviours, Check out to specific local branch
