### ISSUE TITLE
Unsuccessful build may be stated as Success

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-VirtualMachine#30]
In https://github.com/vais-ral/CCPi-Framework/blob/master/build/jenkins-build.sh, we need `bash -e` to make `bash` fail hard. Without `-e` bash continues running the script and exits with the status of the last command it runs (which is `echo git branch is not master, will not upload to anaconda.`).

See https://github.com/vais-ral/CCPi-Framework/issues/206

**Comment by TomasKulhanek** [comment]
testing bash -xe in all jenkins build.
