### ISSUE TITLE
VM doesn't react to mouse clicks

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-VirtualMachine#36]
This is somehow a known bug. 

click Alt-F4 to logout and log in again. 

For some reasons the VM starts already logged in.

**Comment by TomasKulhanek** [comment]
fixed in kernel 3.10.0-957.10.1 and in westlife-eu/scientific_7_gui vagrant box version 19.3.7.6. For old installation do kernel update inside VM by: `sudo yum -y update`

Before creating new VM, call `vagrant box update`

```
$ vagrant box update
...
==> default: Updating 'westlife-eu/scientific_7_gui' with provider 'virtualbox'  from version                                                                     ==> default: '19.2.7.6' to '19.3.7.6'...
...
```
then any other `vagrant up` should boot with new kernel without this bug.
