### ISSUE TITLE
install from binaries to install python 3.5 by default

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-VirtualMachine#5]
Does [this](https://github.com/vais-ral/CCPi-VirtualMachine/blob/master/vm-from-binaries/bootstrap.sh#L12) line install python 3.5. Most of the binaries are available for Python 3.5 only. 

`conda create -q -y --name py3 python=3`

**Comment by TomasKulhanek** [comment]
Installs python 3.7. I noticed that it’s downgraded by subsequent conda install to 3.5.

**Comment by paskino** [comment]
Should we force 3.5?

**Comment by TomasKulhanek** [comment]
If it's not really needed I prefer major version.

**Comment by TomasKulhanek** [comment]
consolidated all conda install into one command - conda determine python version based on package requirement.
