### ISSUE TITLE
VM appliance file is 3.1 Gb

### ISSUE THREAD

**Issue by paskino** [vais-ral/CCPi-VirtualMachine#6]
In the PETMR project we strive to keep the size low and are about 2Gb. This one seems a bit big if we think of distributing it. 
The idea would be to not distribute it but distribute the Vagrantfile, but some users won't install vagrant and VirtualBox.

**Comment by paskino** [comment]
Actually I can't upload it to the ccpi website

**Comment by TomasKulhanek** [comment]
1) the VM can be shrinked and packed, there are tools to do that, but you get still 1-2GB.
2) consider cernvm base OS (cernvm 3 is Scientific Linux 6, cernvm4 is Sceintific Linux 7), build and upload ccpi to some cernvmfs repository and distribute binaries there. Actual size 18 MB-20 MB. Needs internet connection. see example image at https://appdb.egi.eu/store/vappliance/d6.1.virtualfoldervm - btw. it's not one hour task.

**Comment by paskino** [comment]
2 Gb is fine. How would I shrink it?

**Comment by TomasKulhanek** [comment]
clean guest system - https://gist.github.com/TomasKulhanek/fb3554f1265fb9b9fc71310a2678a0bc
then EITHER shrink it e.g. with virtualbox tools - e.g. https://stackoverflow.com/a/49499286/1374834 
OR shrink it with vagrant `vagrant package --base <vritualboc-virtualmachine-name> --output <output-filename.box>` then output-filename.box is in fact zip archive containing virtualbox VM - you can extract and distribute.

**Comment by TomasKulhanek** [comment]
base VM is <600 MB in case of CernVM <20 MB. vagrant script or contextualization in cernvm will make it with ccpi software installed.
